### PR TITLE
Add Python 3.12 support

### PR DESCRIPTION
**Pull request by tseaver**

### CODE REVIEW

**Comment by dataflake** [comment]
Is there a specific reason for dropping Python 3.7? The tests appear to run fine.

**Comment by tseaver** [comment]
Python 3.7 is EOL, but I can revert that bit if you like.  Whatever machinery is in play is *not* pushing this package (or ZConfig) to have official 3.12 support, which was my goal.

**Review by dataflake — APPROVED** [review]

**Comment by dataflake** [comment]
The scripts under meta/config are not run in any automated fashion. It's simply a matter of "if I touch package X I will run the configuration script on that repo to pick up the latest changes". I have done so now.

**Comment by d-maurer** [comment]
Jens Vagelpohl wrote at 2024-5-2 22:09 -0700:
>The scripts under meta/config are not run in any automated fashion. It's simply a matter of "if I touch package X I will run the configuration script on that repo to pick up the latest changes". I have done so now.

Is is really "whenever I TOUCH" or more "when I work towards the next release
or want to chenge something for new Python versions or the GHA workflow"?

I ask because we usually tend to focus PRs to a single purpose.
Additional changes from "meta/config" could make reviews more difficult
as they change files typical developpers may not be familiar with.

**Comment by dataflake** [comment]
OK, whenever working towards a release is a better description. I personally tend to run it whenever I touch a package that is clearly outdated as a preparatory step before making any real changes. That way I know I have a "good known state" as far as package configurations go.

**Comment by dataflake** [comment]
@icemac @tseaver Can you please add me to https://pypi.org/project/zdaemon/ so I can publish a release?

**Comment by tseaver** [comment]
@dataflake I have added you as an owner.  Thanks for pushing the two releases out!

**Comment by dataflake** [comment]
Thanks @tseaver. Release 5.1 is now published.

**Pull request merged**
